services:
  relayer:
    build:
      context: .
      dockerfile: Dockerfile
      target: relayer
    ports:
      - 3111:3111
      # - 3112:3112
    environment:
      - NEON_ETH_RPC_URL=https://devnet.neonevm.org
      - NEON_PRIVATE_KEY=efb03e3f4fd8b3d7f9b14de6c6fb95044e2321d6bcb9dfe287ba987920254044
      - NEON_TOKEN_BRIDGE_ADDRESS=0xC7A204bDBFe983FCD8d8E61D02b475D4073fF97e
      - PORT=3111
      - TESTNET_MODE=1
    restart: always
